version: '3'
services:
  dashboard:
    build: dashboard/
    ports:
      - '8080:80'
  entrypoint:
    build: entrypoint/
    ports:
      - '4000:80'
    environment:
      - KAFKA_VERSION=1.1
      - ROUTE=/v1/tickets
      - TOPIC_INPUT=input_tickets
      - BOOTSTRAP_SERVERS=kafka:9092
      - VALUE_SERIALIZER=json
      - COMPRESSION=gzip
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
  spark:
    image: 'sequenceiq/spark:latest'
    ports:
      - '8088:8088'
      - '8042:8042'

