version: '3.5'
services:
  frenetic-shopping-generator:
    image: admo120104/ticketoc:frenetic-shopping-generator
    build: frenetic-shopping/generator
    command: [
      "./wait-for-it.sh", "entrypoint:80",     "--",
      "./wait-for-it.sh", "schema-registry:80", "--",
      "./wait-for-it.sh", "generator-db:27017", "--",
      "python", "generator.py",
    ]
    environment:
      ENTRYPOINT: entrypoint:80
      SCHEMA_REGISTRY: schema-registry:80
      GENERATOR_DB: generator-db:27017
    depends_on:
      - frenetic-shopping-db
      - generator-db
    networks:
      - default
      - ticketoc_generator-net
  frenetic-shopping-generator-2:
    image: admo120104/ticketoc:frenetic-shopping-generator
    build: frenetic-shopping/generator
    command: [
      "./wait-for-it.sh", "entrypoint:80",     "--",
      "./wait-for-it.sh", "schema-registry:80", "--",
      "./wait-for-it.sh", "generator-db:27017", "--",
      "python", "generator.py", "-s", "1337"
    ]
    environment:
      ENTRYPOINT: entrypoint:80
      SCHEMA_REGISTRY: schema-registry:80
      GENERATOR_DB: generator-db:27017
    depends_on:
      - frenetic-shopping-db
      - generator-db
    networks:
      - default
      - ticketoc_generator-net
  generator-db:
    image: mongo:latest
    environment:
      MONGO_DATA_DIR: /usr/data/db
      MONGO_LOG_DIR: /dev/null
    volumes:
      - ./frenetic-shopping/db:/usr/data/db
    command: mongod --smallfiles --logpath=/dev/null
  frenetic-shopping-db:
    image: admo120104/ticketoc:frenetic-shopping-db
    build: frenetic-shopping/db
    depends_on:
      - generator-db
networks:
  ticketoc_generator-net:
    external: true
