version: '3.2'
services:
  dashboard:
    build: dashboard/
    ports:
      - 8080:80
  entrypoint:
    build: entrypoint/
    ports:
      - 4000:80
    environment:
      KAFKA_VERSION: 1.1
      KAFKA_CONNECT: kafka:9092
      ROUTE: /v1/tickets
      TOPIC: input_tickets
      VALUE_SERIALIZER: json
      COMPRESSION: gzip
    networks:
      - generator-net
  cash-clasp:
    build: cash-clasp/
    ports:
      - 40510:40510
  zookeeper:
    image: zookeeper:latest
    ports:
      - 2181:2181
  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - 9092:9092
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_HOST_NAME: 172.17.0.1:9092
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
  spark:
    image: sequenceiq/spark:latest
    ports:
      - '8088:8088'
      - '8042:8042'
networks:
  generator-net:
    driver: bridge
