version: '3.2'
services:
  frenetic-shopping:
    build: frenetic-shopping/app
    links:
      - mongodb
    networks:
      - ticketoc_generator-net
      - default
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    environment:
      MONGO_DATA_DIR: /usr/data/db
      MONGO_LOG_DIR: /dev/null
    volumes:
      - ./frenetic-shopping/db:/usr/data/db
    ports:
      - 27018:27017
    command: mongod --smallfiles --logpath=/dev/null
    networks:
      - default
  mongo_seed:
    build: frenetic-shopping/db
    links:
      - mongodb
    networks:
      - default
networks:
  ticketoc_generator-net:
    external: true
