version: '3.5'
services:
  frenetic-shopping:
    image: admo120104/ticketoc:frenetic-shopping-app
    build: frenetic-shopping/app
    links:
      - mongodb
    networks:
      - ticketoc_generator-net
  mongodb:
    image: mongo:latest
    environment:
      MONGO_DATA_DIR: /usr/data/db
      MONGO_LOG_DIR: /dev/null
    volumes:
      - ./frenetic-shopping/db:/usr/data/db
    ports:
      - 27018:27017
    command: mongod --smallfiles --logpath=/dev/null
  mongo_seed:
    image: admo120104/ticketoc:frenetic-shopping-db
    build: frenetic-shopping/db
    links:
      - mongodb
networks:
  ticketoc_generator-net:
    external: true
