version: '3.5'
services:
  frenetic-shopping-generator:
    image: admo120104/ticketoc:frenetic-shopping-generator
    build: frenetic-shopping/generator
    command: ["./wait-for-it.sh", "entrypoint:80", "--", "./wait-for-it.sh", "schema-registry:80", "--", "python", "generator.py"]
    depends_on:
      - frenetic-shopping-db
    networks:
      - default
      - ticketoc_generator-net
  mongodb:
    image: mongo:latest
    environment:
      MONGO_DATA_DIR: /usr/data/db
      MONGO_LOG_DIR: /dev/null
    volumes:
      - ./frenetic-shopping/db:/usr/data/db
    command: mongod --smallfiles --logpath=/dev/null
  frenetic-shopping-db:
    image: admo120104/ticketoc:frenetic-shopping-db
    build: frenetic-shopping/db
    depends_on:
      - mongodb
networks:
  ticketoc_generator-net:
    external: true
