version: '3'
services:
  dashboard:
    build: ./../dashboard/
    #context: ./../dashboard/
    #dockerfile: Dockerfile
    ports:
      - '8080:80'
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
  mongo:
    image: mongo
    ports:
      - '27017:27017'
  spark:
    image: 'sequenceiq/spark'
    ports:
      - '8088:8088'
      - '8042:8042'

