version: "3"
services:
  kafka:
    image: wurstmeister/kafka:2.12-2.1.0
    hostname: kafka
    environment:
      KAFKA_ZOOKEEPER_CONNECT: kafka:2181/kafka
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_PORT: 9092
    ports:
      - 9092
      - 2181

